apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-directories-generator-ex1
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Ravi-Baligar/argocd
      revision: main
      directories:
      - path: resources/*
  template:
    metadata:
      name: '{{path.basename}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/Ravi-Baligar/argocd
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-ns'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
